apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-deploy-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: helm-deploy-service
  replicas: 1
  template:
    metadata:
      labels:
        run: helm-deploy-service
    spec:
      serviceAccountName: keptn-helm-service
      containers:
      - name: helm-deploy-service
        image: keptn/helm-deploy-service:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 10999
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
        - name: CONFIGURATION_SERVICE
          value: 'http://configuration-service:8080'
        - name: EVENTBROKER
          value: 'http://event-broker/keptn'
        - name: ENVIRONMENT
          value: 'production'
      - name: distributor
        image: keptn/distributor:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 10999
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PUBSUB_URL
            value: 'nats://keptn-nats-cluster'
          - name: PUBSUB_TOPIC
            value: 'sh.keptn.event.deployment.triggered'
          - name: PUBSUB_RECIPIENT
            value: '127.0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: helm-deploy-service
  namespace: keptn
  labels:
    run: helm-deploy-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: helm-deploy-service